//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesforceMetadata.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAndAPIFileLocation {
            get {
                return ((string)(this["UserAndAPIFileLocation"]));
            }
            set {
                this["UserAndAPIFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SharedSecretLocation {
            get {
                return ((string)(this["SharedSecretLocation"]));
            }
            set {
                this["SharedSecretLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Salt {
            get {
                return ((string)(this["Salt"]));
            }
            set {
                this["Salt"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.salesforce.com/services/Soap/u/61.0")]
        public string SalesforceMetadata_PartnerWSDL_SforceService {
            get {
                return ((string)(this["SalesforceMetadata_PartnerWSDL_SforceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.salesforce.com/services/Soap/m/61.0")]
        public string SalesforceMetadata_MetadataWSDL_MetadataService {
            get {
                return ((string)(this["SalesforceMetadata_MetadataWSDL_MetadataService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.salesforce.com/services/Soap/T/61.0")]
        public string SalesforceMetadata_ToolingWSDL_SforceServiceService {
            get {
                return ((string)(this["SalesforceMetadata_ToolingWSDL_SforceServiceService"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60.0")]
        public string DefaultAPI {
            get {
                return ((string)(this["DefaultAPI"]));
            }
            set {
                this["DefaultAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DevelopmentSelectedFolder {
            get {
                return ((string)(this["DevelopmentSelectedFolder"]));
            }
            set {
                this["DevelopmentSelectedFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DevelopmentDeploymentFolder {
            get {
                return ((string)(this["DevelopmentDeploymentFolder"]));
            }
            set {
                this["DevelopmentDeploymentFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutomationReportLastReadLocation {
            get {
                return ((string)(this["AutomationReportLastReadLocation"]));
            }
            set {
                this["AutomationReportLastReadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutomationReportLastSaveLocation {
            get {
                return ((string)(this["AutomationReportLastSaveLocation"]));
            }
            set {
                this["AutomationReportLastSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigurationWorkbookLastReadLocation {
            get {
                return ((string)(this["ConfigurationWorkbookLastReadLocation"]));
            }
            set {
                this["ConfigurationWorkbookLastReadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfigurationWorkbookLastSaveLocation {
            get {
                return ((string)(this["ConfigurationWorkbookLastSaveLocation"]));
            }
            set {
                this["ConfigurationWorkbookLastSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlExtractSaveToLocation {
            get {
                return ((string)(this["UrlExtractSaveToLocation"]));
            }
            set {
                this["UrlExtractSaveToLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeploymentPackageLastSaveLocation {
            get {
                return ((string)(this["DeploymentPackageLastSaveLocation"]));
            }
            set {
                this["DeploymentPackageLastSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeploymentPackageLastReadLocation {
            get {
                return ((string)(this["DeploymentPackageLastReadLocation"]));
            }
            set {
                this["DeploymentPackageLastReadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LWCLastReadLocation {
            get {
                return ((string)(this["LWCLastReadLocation"]));
            }
            set {
                this["LWCLastReadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LWCLastSaveLocation {
            get {
                return ((string)(this["LWCLastSaveLocation"]));
            }
            set {
                this["LWCLastSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetadataComparisonLastCompareFrom {
            get {
                return ((string)(this["MetadataComparisonLastCompareFrom"]));
            }
            set {
                this["MetadataComparisonLastCompareFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetadataComparisonLastCompareTo {
            get {
                return ((string)(this["MetadataComparisonLastCompareTo"]));
            }
            set {
                this["MetadataComparisonLastCompareTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetadataToolingLastReadFrom {
            get {
                return ((string)(this["MetadataToolingLastReadFrom"]));
            }
            set {
                this["MetadataToolingLastReadFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ObjectModificationLastReadFrom {
            get {
                return ((string)(this["ObjectModificationLastReadFrom"]));
            }
            set {
                this["ObjectModificationLastReadFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetadataLastSaveToLocation {
            get {
                return ((string)(this["MetadataLastSaveToLocation"]));
            }
            set {
                this["MetadataLastSaveToLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSearchLocation {
            get {
                return ((string)(this["LastSearchLocation"]));
            }
            set {
                this["LastSearchLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApiVersionUpdaterLastReadLocation {
            get {
                return ((string)(this["ApiVersionUpdaterLastReadLocation"]));
            }
            set {
                this["ApiVersionUpdaterLastReadLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SobjectReportLocation {
            get {
                return ((string)(this["SobjectReportLocation"]));
            }
            set {
                this["SobjectReportLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTextEditorPath {
            get {
                return ((string)(this["DefaultTextEditorPath"]));
            }
            set {
                this["DefaultTextEditorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetadataFolderPath {
            get {
                return ((string)(this["MetadataFolderPath"]));
            }
            set {
                this["MetadataFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParseMetadataFolderaPath {
            get {
                return ((string)(this["ParseMetadataFolderaPath"]));
            }
            set {
                this["ParseMetadataFolderaPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepositoryPath {
            get {
                return ((string)(this["RepositoryPath"]));
            }
            set {
                this["RepositoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IDEProjectRoot {
            get {
                return ((string)(this["IDEProjectRoot"]));
            }
            set {
                this["IDEProjectRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DebugLogPath {
            get {
                return ((string)(this["DebugLogPath"]));
            }
            set {
                this["DebugLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MetadataAynchrounsThreads {
            get {
                return ((int)(this["MetadataAynchrounsThreads"]));
            }
            set {
                this["MetadataAynchrounsThreads"] = value;
            }
        }
    }
}
